name: Auto Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Auto Tag and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Generate tag (semver bump)
        id: tagger
        uses: anothrnick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch  # can be: patch / minor / major

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o openvpn-agent-linux-amd64 ./cmd/agent

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.new_tag }}
          files: openvpn-agent-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
